#CI项目名
name: IWRT-Rockchip

on:
  #自动编译：每天早上6点
  schedule:
    - cron: 0 22 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_build:
    uses: ./.github/workflows/OWRT-CORE.yml
    #其他人直接调用我写好的OWRT-CORE.yml
    #uses: VIKINGYFY/OpenWRT-CI/.github/workflows/OWRT-CORE.yml@main
    with:
      #编译平台
      OWRT_TARGET: Rockchip
      #默认主题
      OWRT_THEME: argon
      #默认主机名
      OWRT_NAME: IWRT
      #默认密码，仅作展示，请勿乱改
      OWRT_PW: 无
      #默认IP地址
      OWRT_IP: 192.168.2.1
      #默认源码
      OWRT_URL: https://github.com/immortalwrt/immortalwrt.git
