name: OpenWRT-TEST  #设备型号，请用大写字母，请勿乱写

on:
  workflow_dispatch:

env:
  DEVICE_NAME: TEST  #设备型号，请用大写字母，请勿乱写
  DEVICE_TYPE: arm64  #设备内核类型，请用小写字母，请勿乱写
  DEVICE_IP: 192.168.2.1  #设备默认登陆地址
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  LEDE_URL: https://github.com/coolsnowwolf/lede.git
  LIST_URL: https://raw.githubusercontent.com/VIKINGYFY/OpenWRT-LEDE/main/Lists

permissions: write-all

jobs:
  build_openwrt:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E rm -rf $(curl -sfL $LIST_URL/Remove_List.txt)
          sudo -E apt -yqq update
          sudo -E apt -yqq purge $(curl -sfL $LIST_URL/Purge_List.txt)
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq install $(curl -sfL $LIST_URL/Install_List.txt)
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq clean
          sudo -E apt -yqq autoclean
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Check Projects
        uses: actions/checkout@v3

      - name: Check Scripts
        run: |
          cd ./Scripts

          chmod +x ./*.sh
          dos2unix ./*.sh

      - name: Clone LEDE Code
        run: |
          git clone --depth=1 --single-branch $LEDE_URL

      - name: Update Feeds
        run: |
          cd ./lede

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom Scripts
        run: |
          cd ./lede
          $GITHUB_WORKSPACE/Scripts/Settings.sh

          cd ./package
          $GITHUB_WORKSPACE/Scripts/Plugins.sh

      - name: Custom Settings
        run: |
          cd ./lede

          rm -rf ./tmp && rm -rf ./.config*
          cat $GITHUB_WORKSPACE/Config/R4S.txt $GITHUB_WORKSPACE/Config/General.txt >> .config

          make defconfig

      - name: Package Firmware
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV
          echo "DEVICE_IP=$DEVICE_IP" >> $GITHUB_ENV

          cd ./lede && mkdir ./test
          cp -rf ./.config ./test/R4S_config_$BUILD_DATE.txt

      - name: Release Firmware
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.DEVICE_NAME}}_Config_${{env.BUILD_DATE}}
          files: ./lede/test/*.txt
          body: |
            测试专用

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
