#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#

name: OpenWRT-TEST

on:
  workflow_dispatch:

env:
  DEVICE_NAME: TEST
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build_openwrt:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Create Test File
        run: |
          mkdir -p ./test/t1/t2

          cd ./test/t1/t2
          touch TEST.txt

          echo $DEVICE_NAME

          #cat >> TEST.txt <<EOF
          #EOF

      - name: Package Test File
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

          cp -rf $(find ./test/ -type f -name "*$DEVICE_NAME*.*") ./test/

          cd ./test
          zip -pmq $DEVICE_NAME_$BUILD_DATE.zip *.*

      - name: Release Test
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $DEVICE_NAME_${{env.BUILD_DATE}}
          files: ./test/*.zip
          body: |
            测试一下！
            123
            abc
