#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#

name: OpenWRT-TEST

on:
  workflow_dispatch:

env:
  DEVICE_NAME: TEST
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build_openwrt:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Create Test File
        run: |
          mkdir -p ./test/t1/t2

          cd ./test/t1/t2
          touch TEST.txt

          cat >> TEST.txt <<EOF
          $DEVICE_NAME
          ${{DEVICE_NAME}}
          ${{env.DEVICE_NAME}}
          EOF

      - name: Package Test File ${{DEVICE_NAME}}
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

          cp -rf $(find ./test/ -type f -name '*$DEVICE_NAME*.*') ./test/
          zip -pmq TEST_$BUILD_DATE.zip *.*

      - name: Release Firmware ${{env.DEVICE_NAME}}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: TEST_${{env.BUILD_DATE}}
          files: ./test/*.zip
          body: |
            测试一下！
            123
            abc

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 6
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
