#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#

name: OpenWRT-TEST

on:
  schedule:
    - cron: 0 6 */2 * *

  push:
    branches: [main]

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  CORE_VER: https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/core_version
  CORE_TUN: https://github.com/vernesong/OpenClash/raw/core/dev/premium/clash-linux-arm64
  CORE_DEV: https://github.com/vernesong/OpenClash/raw/core/dev/dev/clash-linux-arm64.tar.gz
  CORE_MATE: https://github.com/vernesong/OpenClash/raw/core/dev/meta/clash-linux-arm64.tar.gz

jobs:
  build_openwrt:
    name: Build Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lede
    steps:
      - name: Clone LEDE Code
        run: |
          git clone --depth=1 --single-branch https://github.com/coolsnowwolf/lede.git

      - name: Update Plugins
        run: |
          ls -a
          cd ./lede/package
          git clone --depth=1 --single-branch https://github.com/gngpp/luci-theme-design.git
