#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#

name: OpenWRT-TEST

on:
  workflow_dispatch:

env:
  TEST_NAME: TEST
  T1_NAME: R4S
  T2_NAME: General
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build_openwrt:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Create Test File
        run: |
          mkdir -p ./test/t1/t2

          cd ./test
          touch test.txt
          cat "$GITHUB_WORKSPACE/Config-$T1_NAME" "$GITHUB_WORKSPACE/Config-$T2_NAME" > test.txt

      - name: Package Test File
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "TEST_NAME=$TEST_NAME" >> $GITHUB_ENV

          #cp -rf $(find ./test/ -type f -name "*$TEST_NAME*.*") ./test/

          cd ./test
          zip -pmq "$TEST_NAME"_"$BUILD_DATE".zip *.*

      - name: Release Test
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.TEST_NAME}}_${{env.BUILD_DATE}}
          files: ./test/*.zip
          body: |
            测试一下！
            $TEST_NAME
            "$TEST_NAME"
            ${{env.TEST_NAME}}
