name: OWRT-TEST

on:
  workflow_dispatch:

env:
  CI_RUNS: 2
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build_test:
    name: Build TEST
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: $CI_RUNS
