name: OWRT-TEST  #CI项目名

on:
  workflow_dispatch:  #手动编译

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build_test:
    name: Build TEST
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 3
